apiVersion: v1
kind: Pod
metadata:
  name: neo4j-dumper
  namespace: moreillon
spec:
  enableServiceLinks: false
  restartPolicy: Never
  containers:
    - name: neo4j-dumper
      image: neo4j:5.15.0
      command: ["neo4j-admin"]
      args:
        [
          "database",
          "dump",
          "neo4j",
          "--to-path=/data/dumps/",
          "--overwrite-destination=true",
        ]
      volumeMounts:
        - mountPath: /data
          name: data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: neo4j
