apiVersion: v1
kind: Pod
metadata:
  name: neo4j-migrator
  namespace: moreillon
spec:
  enableServiceLinks: false
  restartPolicy: Never
  containers:
    - name: neo4j-migrator
      image: neo4j:5.12.0
      command: ["neo4j-admin"]
      args: ["database", "migrate", "neo4j", "--force-btree-indexes-to-range"]
      volumeMounts:
        - mountPath: /data
          name: data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: neo4j
