apiVersion: v1
kind: Pod
metadata:
  name: neo4j-restorer
spec:
  enableServiceLinks: false
  restartPolicy: Never
  containers:
    - name: neo4j-restorer
      image: neo4j:5.12.0
      command: ["neo4j-admin"]
      args:
        [
          "database",
          "load",
          "--from-path=/data/dumps",
          "neo4j",
          "--overwrite-destination=true",
        ]
      volumeMounts:
        - mountPath: /data
          name: data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: neo4j
